apiVersion: v1
kind: ReplicationController
metadata:
        name: mysql
spec:
        replicas: 1
        selector:
                app: mysql
        template:
                metadata:
                        labels:
                                app: mysql
                spec:
                        containers:
                                - name: mysql
                                  image: 10.234.138.130:5000/renren/mysql
                                  ports:
                                          - containerPort: 3306
                                  env:
                                          - name: MYSQL_ROOT_PASSWORD
                                            value: "111111"
---
apiVersion: v1
kind: Service
metadata:
        name: mysql1
spec:
        type: NodePort
        ports:
                - port: 3307
                  targetPort: 3306
        selector:
                app: mysql
